galaxy_info:
  author: Tim Hourigan
  description: Install pyenv
  license: MIT
  min_ansible_version: 2.5
  role_name: pyenv
  namespace: timhourigan
  platforms:
    - name: Debian
      versions:
        - bullseye
    - name: Fedora
      versions:
        - 34
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - pyenv
dependencies: []
