---
- name: Install dependencies
  ansible.builtin.package:
    name: "{{ alacritty_dependencies[ansible_distribution] }}"
    state: present
  become: yes

- name: Build
  community.general.cargo:
    name: alacritty
    state: latest
  environment:
    PATH: /home/{{ username }}/.cargo/bin/:{{ ansible_env.PATH }}
  become: yes
  become_user: "{{ username }}"

- name: Copy binary
  ansible.builtin.copy:
    src: /home/{{ username }}/.cargo/bin/alacritty
    dest: /usr/local/bin/alacritty
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  become: yes

- name: Create temporary repository directory
  ansible.builtin.tempfile:
    state: directory
    suffix: alacrittyrepo
  register: repo_dir

- name: Install git
  ansible.builtin.package:
    name: git
    state: present
  become: yes

- name: Clone repository
  ansible.builtin.git:
    repo: https://github.com/alacritty/alacritty.git
    dest: "{{ repo_dir.path }}"
    single_branch: yes
    version: master

- name: Set terminfo
  ansible.builtin.command:
    cmd: tic -xe alacritty,alacritty-direct {{ repo_dir.path }}/extra/alacritty.info
    creates: /etc/terminfo/a/alacritty
  become: yes

- name: Copy icon
  ansible.builtin.copy:
    src: "{{ repo_dir.path }}/extra/logo/alacritty-term.svg"
    dest: /usr/share/pixmaps/Alacritty.svg
    remote_src: yes
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Remove temporary repo directory
  ansible.builtin.file:
    path: "{{ repo_dir.path }}"
    state: absent
  when: repo_dir.path is defined

# sudo desktop-file-install extra/linux/Alacritty.desktop
# sudo update-desktop-database


# install man-db
#
# sudo mkdir -p /usr/local/share/man/man1
# gzip -c extra/alacritty.man | sudo tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null
# gzip -c extra/alacritty-msg.man | sudo tee /usr/local/share/man/man1/alacritty-msg.1.gz > /dev/null

# 
#
# Playbook run took 0 days, 0 hours, 1 minutes, 25 seconds
# CRITICAL Idempotence test failed because of the following tasks:
# *  => alacrittyterm : Create temporary repository directory
# *  => alacrittyterm : Create temporary repository directory
# *  => alacrittyterm : Create temporary repository directory
# *  => alacrittyterm : Clone repository
# *  => alacrittyterm : Clone repository
# *  => alacrittyterm : Clone repository
# *  => alacrittyterm : Set terminfo
# *  => alacrittyterm : Remove temporary repo directory
# *  => alacrittyterm : Remove temporary repo directory
# *  => alacrittyterm : Remove temporary repo directory
# WARNING  An error occurred during the test sequence action: 'idempotence'. Cleaning up.
# INFO     Running default > cleanup
# WARNING  Skipping, cleanup playbook not configured.
