---
- name: Install dependencies
  ansible.builtin.package:
    name: "{{ alacritty_dependencies[ansible_distribution] }}"
    state: present
  become: yes

- name: Build
  community.general.cargo:
    name: alacritty
    state: latest
  environment:
    PATH: /home/{{ username }}/.cargo/bin/:{{ ansible_env.PATH }}
  become: yes
  become_user: "{{ username }}"

- name: Copy binary
  ansible.builtin.copy:
    src: /home/{{ username }}/.cargo/bin/alacritty
    dest: /usr/local/bin/alacritty
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  become: yes
