---
nix_version: 2.9.1
nix_install_script: install
nix_installer_url: https://releases.nixos.org/nix/nix-{{ nix_version }}/{{ nix_install_script }}
nix_key: B541D55301270E0BCF15CA5D8170B4726D7198DE
nix_path: /nix
nix_dependencies:
  {
    Fedora:
      [
        gnupg2
      ],
    Debian:
      [
        gnupg2
      ],
    Ubuntu:
      [
        gnupg2
      ]
  }
