---
- name: Install
  ansible.builtin.pip:
    name: pipx
    extra_args: --user
  become: yes
  become_user: "{{ username }}"

- name: Run ensurepath
  ansible.builtin.command: python3 -m pipx ensurepath
  become: yes
  become_user: "{{ username }}"
  changed_when: false
