---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - python3-venv
      - python3-pip
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Install
  ansible.builtin.pip:
    name: pipx
    extra_args: --user
  become: yes
  become_user: "{{ username }}"

- name: Run ensurepath
  ansible.builtin.command: python3 -m pipx ensurepath
  changed_when: false
  become: yes
  become_user: "{{ username }}"
