---
- name: Check if aleady installed
  ansible.builtin.stat:
    path: "{{ dotfiles_path }}"
  register: dotfiles_installed

- name: Install dependencies
  ansible.builtin.package:
    name: "{{ dotfiles_dependencies[ansible_distribution] }}"
    state: present
  become: yes
  when: not dotfiles_installed.stat.exists

- name: Clone repository
  ansible.builtin.git:
    repo: "{{ dotfiles_repository }}"
    dest: "{{ dotfiles_path }}"
    single_branch: yes
    version: main
  become: yes
  become_user: "{{ username }}"
  when: not dotfiles_installed.stat.exists


# Stow a list of dotfiles
