---
- name: Configure
  ansible.builtin.template:
    src: 00aptproxy.j2
    dest: /etc/apt/apt.conf.d/00aptproxy
    owner: root
    group: root
    mode: 0644
  become: yes
  when: ansible_os_family == "Debian"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"
