---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Include vars
      include_vars:
        file: vars/main.yml
    - name: Create user
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
    - name: Setup APT Proxy
      include_role:
        name: apt_proxy
      when:
        - ansible_os_family == "Debian"
        - apt_proxy_url is defined
    - name: Update apt cache
      apt:
        update_cache: true
      when: ansible_os_family == "Debian"
    - name: Update dnf cache
      dnf:
        update_cache: true
      when: ansible_os_family == "RedHat"
    - name: Install standard packages, required by Ansible modules
      package:
        name:
          - unzip
        state: present
  tasks:
    - name: Include roles
      include_role:
        name: "{{ item }}"
      with_items:
        - autojump
        - bat
        - exa
        - fzf
        - ripgrep
        # Removed for now, due to time taken to install
        # - rust
        - pipx
