---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Include vars
      include_vars:
        file: vars/main.yml
    - name: Create user
      ansible.builtin.user:
        name: "{{ username }}"
    - name: Update apt cache
      apt:
        update_cache: true
      when: ansible_os_family == "Debian"
    - name: Update dnf cache
      dnf:
        update_cache: true
      when: ansible_os_family == "RedHat"
  tasks:
    - name: Include roles
      include_role:
        name: "{{ item }}"
      with_items:
        - autojump
        - bat
        - fzf
        - rust
