---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Include vars
      include_vars:
        file: vars/main.yml
    - name: Create user
      ansible.builtin.user:
        name: "{{ username }}"
    # Include if using an APT Proxy
    # - name: Setup APT Proxy
    #   include_role:
    #     name: apt_proxy
    #   when: ansible_os_family == "Debian"
    - name: Update apt cache
      apt:
        update_cache: true
      when: ansible_os_family == "Debian"
    - name: Update dnf cache
      dnf:
        update_cache: true
      when: ansible_os_family == "RedHat"
    - name: Install standard packages
      package:
        name:
          - unzip
        state: present
  tasks:
    - name: Include roles
      include_role:
        name: "{{ item }}"
      with_items:
        - autojump
        - bat
        - exa
        - fzf
        - ripgrep
        # Removed for now, due to time taken to install
        # - rust
