---
- name: Verify
  hosts: all
  tasks:
  - name: Gather package facts
    ansible.builtin.package_facts:
      manager: auto
  - name: Include vars
    ansible.builtin.include_vars:
      file: vars/main.yml
  # Run checks
  - import_tasks: checks/autojump.yml
  - import_tasks: checks/bat.yml
  - import_tasks: checks/exa.yml
  - import_tasks: checks/fzf.yml
  - import_tasks: checks/go.yml
  - import_tasks: checks/ripgrep.yml
  # Removed for now, due to time taken to install
  # - import_tasks: checks/rust.yml
  - import_tasks: checks/pipx.yml
  - name: Check apt_proxy
    import_tasks: checks/apt_proxy.yml
    when: apt_proxy_url is defined
