---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Gather package facts
    ansible.builtin.package_facts:
      manager: auto
  - name: Include vars
    include_vars:
      file: vars/main.yml
  # Run checks
  - import_tasks: checks/autojump.yml
  - import_tasks: checks/fzf.yml
  - import_tasks: checks/rust.yml
