---
- hosts: all
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
      become: yes
      when: ansible_os_family == "Debian"
    - name: Update dnf cache
      dnf:
        update_cache: true
      become: yes
      when: ansible_os_family == "RedHat"
  roles:
    - roles/autojump
    - roles/fzf
    - roles/go
    - roles/nix
    - roles/pipx
    - roles/pyenv
    - roles/rust
