galaxy_info:
  author: Tim Hourigan
  description: Install fzf
  license: MIT
  min_ansible_version: 2.5
  role_name: fzf
  namespace: timhourigan
  platforms:
  - name: Debian
    versions:
      - bullseye
  - name: Fedora
    versions:
    - 34
  - name: Ubuntu
    versions:
    - focal
  galaxy_tags:
    - fzf
dependencies: []
