---
- name: Check if aleady installed
  ansible.builtin.stat:
    path: /home/{{ username }}/.pyenv/bin/pyenv
  register: pyenv_installed

- name: Install dependencies
  ansible.builtin.package:
    name: "{{ pyenv_dependencies[ansible_distribution] }}"
    state: present
  become: yes
  when: not pyenv_installed.stat.exists

- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: pyenv
  register: installer_dir
  become: yes
  become_user: "{{ username }}"
  when: not pyenv_installed.stat.exists

- name: Download pyenv-installer
  ansible.builtin.get_url:
    url: "{{ pyenv_installer_url }}"
    dest: "{{ installer_dir.path }}"
    mode: 0544
  become: yes
  become_user: "{{ username }}"
  when: not pyenv_installed.stat.exists

- name: Run pyenv-installer
  ansible.builtin.command:
    cmd: "{{ installer_dir.path }}/pyenv-installer --quiet -y"
    creates: /home/{{ username }}/.pyenv/bin/pyenv
  become: yes
  become_user: "{{ username }}"
  when: not pyenv_installed.stat.exists

- name: Remove pyenv-installer
  ansible.builtin.file:
    path: "{{ installer_dir.path }}"
    state: absent
  become: yes
  become_user: "{{ username }}"
  when: not pyenv_installed.stat.exists
