---
- name: Check if aleady installed
  ansible.builtin.stat:
    path: /home/{{ username }}/.pyenv/bin/pyenv
  register: pyenv_installed

# 
# TASK [pyenv : Download pyenv-installer] ****************************************
# [WARNING]: Module remote_tmp /home/test.user/.ansible/tmp did not exist and was
# created with a mode of 0700, this may cause issues when running as another
# user. To avoid this, create the remote_tmp dir with the correct permissions
# manually

- name: Install dependencies
  ansible.builtin.package:
    name: "{{ pyenv_dependencies[ansible_distribution] }}"
    state: present
  become: yes
  when: not pyenv_installed.stat.exists

- name: Download pyenv-installer
  ansible.builtin.get_url:
    url: "{{ pyenv_installer_url }}"
    dest: /home/{{ username }}/
    mode: 0544
  become: yes
  become_user: "{{ username }}"
  when: not pyenv_installed.stat.exists

- name: Run pyenv-installer
  ansible.builtin.command:
    cmd: /home/{{ username }}/pyenv-installer --quiet -y
    creates: /home/{{ username }}/.pyenv/bin/pyenv
  become: yes
  become_user: "{{ username }}"
  when: not pyenv_installed.stat.exists

- name: Remove pyenv-installer
  ansible.builtin.file:
    path: /home/{{ username }}/pyenv-installer
    state: absent
  become: yes
  become_user: "{{ username }}"
  when: not pyenv_installed.stat.exists
