---
- name: bat | Verify package is installed
  ansible.builtin.assert:
    that: "'bat' in ansible_facts.packages"

- name: bat | Check for binary
  ansible.builtin.stat:
    path: /usr/bin/bat
  register: bat

- name: bat | Verify binary is present
  ansible.builtin.assert:
    that: bat.stat.exists
