---
- name: bat | Verify package is installed
  assert:
    that: "'bat' in ansible_facts.packages"

- name: bat | Check for binary
  stat:
    path: /usr/bin/bat
  register: bat

- name: bat | Verify binary is present
  assert:
    that: bat.stat.exists
