---
- name: Verify bat is installed
  assert:
    that: "'bat' in ansible_facts.packages"

- name: Check for bat binary
  stat:
    path: /usr/bin/bat
  register: bat
- name: Verify bat is installed
  assert:
    that: bat.stat.exists
