---
- name: exa | Verify package is installed
  ansible.builtin.assert:
    that: "'exa' in ansible_facts.packages"
  when: ansible_distribution == "Debian" or ansible_os_family == "RedHat"

# exa is only in Ubuntu 20.10 onwards, so manually check
- name: exa | Check for binary
  ansible.builtin.stat:
    path: /usr/bin/exa
  register: exa

- name: exa |Verify binary is present
  ansible.builtin.assert:
    that: exa.stat.exists
