---
- name: rust | Check for binary
  ansible.builtin.stat:
    path: /home/{{ username }}/.cargo/bin/rustc
  register: rust

- name: rust | Verify binary is present
  ansible.builtin.assert:
    that: rust.stat.exists
