---
# Package divert required due to a package name clash
- name: Divert and rename batcat for Debian based distros
  community.general.dpkg_divert:
    path: /usr/bin/batcat
    divert: /usr/bin/bat
    rename: yes
  become: yes
  when: ansible_os_family == "Debian"

- name: Install
  package:
    name: bat
    state: present
  become: yes
